coin/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'coin'

urlpatterns = [
    path('', views.coin, name='coin'),
    path('test/', views.coin2, name='coin2'),
]

lotto/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'lotto'

urlpatterns = [
    path('', views.random_lotto, name='random_lotto'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from base.views import index
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    url(r'^lotto/', include('lotto.urls')),
    url(r'^coin/', include('coin.urls')),
    
]

coin/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'base/index.html', {})

coin/views.py
from django.shortcuts import render
import coin.coin_api as c
import coin.telegram_bot as telbot

# Create your views here.
def coin(request):
    a = c.get()
    btc_price = a['data']['XRP']['quote']['KRW']['price']
    return render(request, 'coin/coin.html', {'btc_price':btc_price})

def coin2(request):
    return render(request, 'coin/coin2.html', {})

# -*- coding: utf-8 -*-

# import json
# import requests

# COIN_API_URL = 'https://pro-api.coinmarketcap.com/'

# API_KEY = 'b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c'
# API_SECRET = 'sandbox-api.coinmarketcap.com'

lotto/views.py
import random
from django.contrib import messages

from django.shortcuts import render

# Create your views here.
def random_lotto(request):
    if request.method == 'POST':
        num = request.POST.get('num', None)
        
        if num is not None and num is not "":
            num = int(num)
            lottos = []
            for i in range(0, num):
                lotto = random.sample(range(1, 46), 6)
                lotto.sort()
                print(lotto)
                lottos.append(lotto)
            return render(request, 'lotto/random_lotto.html', {'lottos':lottos})
        else:
            messages.success(request, '정상적인 숫자를 넣어주십쇼잉.')
    return render(request, 'lotto/random_lotto.html', {})

templates/base/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'base/base/header.html' %}
    {% include 'base/base/style.html' %}
    {% block header %}
    {% endblock %}

    <title>손꾸락닷컴</title>
</head> 

<body>
    {% include 'base/base/navbar.html' %}
    {% if messages %}
        <div class="alert alert-success messages">
            {% for message in messages %}
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}<br/>
            </span>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}
    {% endblock %} 

    <hr style="margin: 10px 0px 0px; height: 1px; border: none; background-color: rgb(224, 224, 224);">
    <!-- 여기부터 Footer -->  
    {% include 'base/base/footer.html' %}
    <!-- Footer 끝 --> 

    
{% block javascript %}
{% endblock %}
{% include 'base/base/js.html' %}

</body>

</html>

templates/base/base/header.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0" />
<!-- meta og properties -->

<meta property="og:title" content='손꾸락닷컴'>
<meta property="og:image" content=""> 
<meta property="og:image:width" content="800"/>
<meta property="og:image:height" content="400"/> 
<meta property="og:url" content="https://sggrr.com/"/> 
<meta property="og:site_name" content="손꾸락"/> 
<meta property="og:type" content="website"/>
<meta property="og:description" content="손꾸락닷컴">

<!-- Bootstrap CSS -->
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script> -->

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

<!-- fontawsome CSS -->
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>



<!-- js render -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.11/jsrender.js"></script> -->
<!-- % include 'shop/base/js_template.html' %} -->



<!-- Jquery-confirm JavaScript -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script> -->

<!-- jQuery -->
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css"> -->

templates/base/base/js.html
{% load static %}
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

<!-- CSRF for ajax JS -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

templates/base/base/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand font-ee" href="{% url 'index' %}">손꾸락닷컴</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active font-ee" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled font-ee" aria-current="page" href="#">주식</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active font-ee" aria-current="page" href="{% url 'coin:coin' %}">코인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled font-ee" aria-current="page" href="#">부동산</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active font-ee" aria-current="page" href="{% url 'lotto:random_lotto' %}">로또</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled font-ee" aria-current="page" href="#">기타</a>
          </li>
        </ul>
        <span class="navbar-text font-ee">
            니 손꾸락 내 손꾸락
        </span>
      </div>
    </div>
  </nav>

templates/base/base/style.html
<style>

@font-face {
    font-family: 'Eulyoo1945-SemiBold';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2102-01@1.0/Eulyoo1945-SemiBold.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

.font-ee {
    font-family: 'Eulyoo1945-SemiBold';
}
</style>

templates/base/index.html
{% extends 'base/base.html' %}

{% block content %}
<div class='container' style='margin-top:100px;'>
    <div class='row'>
        <div class='col text-center'>
            <h1 class='font-ee'>WELCOME TO 손꾸락닷컴</h1>
        </div>    
    </div>
    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                손꾸락닷컴#1
            </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    
            ║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║
            ║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄▄▄║║║║║█▌║║║║║║║║║║
            ║║║║║║║║║║▄██▌║║║║║║║║║║║▄▄▄▄▄▄║║▄▄███▌║║║║║██████████║║║║█▌║║║║║║║║║║
            ║║║║║║║║▄████║║║║║║║║║║║▐██████▌▐███▀█▌║║║║║▀▀▀▀▀▀▀║██║║║║█▌║║║║║║║║║║
            ║║║║║▄████████▄║║║║║║║║║║║║║║║█▌║║║║▐█▌║║║║║║║║║║║║▄██║║║║██▄▄███║║║║║
            ║▄█████▀▀║║▀███████▄║║║║║║║║║██║║║║║██║║║║║║║█████████║║║▐█████▀▀║║║║║
            ║███▀▀║║║▄║║║║║▀▀███║║║║║║║║║██║║║║███║║║║║║▐██▀▀▀▀▀║║║║║║█▌║║║║║║║║║║
            ║║║║║║║║▐█║║║║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║▐██▄▄▄▄▄▄▄║║║▐█▌║║║║║║║║║║
            ║▄▄▄║║║║▐█║║║║║║║▄▄▄▄▄▄▄▄║▐█████████████║║║║║█████████║║║▐█║║║║║║║║║║║
            ▐████████████████████████║▐█▀▀▀▀▀██▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║██║║║║║║║║║║██████████████║║║║║║║║║║║
            ║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║▀▀▀▀▀▀▀▀▀▀▀▀██║║║║║║║║║║║
            ║║║║▐█▌║║║║║║║║▄║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║║║║║
            ║║║║▐███████████║║║║║║║║║║║║║║║║║▀║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║
            ║║║║║▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║▄▄▄▄▄║║║║║█▌║║║║║║║║║║║║║║║▄▄▄▄▄▄▄▄║║║▐██║║║║║║║║║║║║║║║║║║║
            ║║║║║▐█████████║║║║║█▌║║║║║║║║║║║║║║▐████████▌║║║██║║║║║║║║║║║║║║║║║║║
            ║║║║║║███▀▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║██▌║▄▄██▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██║║║║║║║║║║║║███████▌║║║║║║║║║████████║▐████▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██▄███████║║║║██▀▀▀▀▀║║║║║║║║║║▀▀▀████║║║▀║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║▐████▀▀▀▀▀▀║║║║█▌║║║║║║║║║║║║║║║▄█████║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║▄║║║║║║█▌║║║║║║║║║║║║║║████▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║▀▀║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║▄▄▄▄▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║██████▄║║║║║║║║║║║║║║║║║║║▐████████████▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▄████║▀██████▄║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║█▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║▐███║║║║║║║▀████▌║║║║║║║║║║║║║║▐█║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▀║║║║║║║║║║║║▀▀║║║║║║║║║║║║║║║▐█▄█████████║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                손꾸락닷컴#2
            </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    
            ║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║
            ║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄▄▄║║║║║█▌║║║║║║║║║║
            ║║║║║║║║║║▄██▌║║║║║║║║║║║▄▄▄▄▄▄║║▄▄███▌║║║║║██████████║║║║█▌║║║║║║║║║║
            ║║║║║║║║▄████║║║║║║║║║║║▐██████▌▐███▀█▌║║║║║▀▀▀▀▀▀▀║██║║║║█▌║║║║║║║║║║
            ║║║║║▄████████▄║║║║║║║║║║║║║║║█▌║║║║▐█▌║║║║║║║║║║║║▄██║║║║██▄▄███║║║║║
            ║▄█████▀▀║║▀███████▄║║║║║║║║║██║║║║║██║║║║║║║█████████║║║▐█████▀▀║║║║║
            ║███▀▀║║║▄║║║║║▀▀███║║║║║║║║║██║║║║███║║║║║║▐██▀▀▀▀▀║║║║║║█▌║║║║║║║║║║
            ║║║║║║║║▐█║║║║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║▐██▄▄▄▄▄▄▄║║║▐█▌║║║║║║║║║║
            ║▄▄▄║║║║▐█║║║║║║║▄▄▄▄▄▄▄▄║▐█████████████║║║║║█████████║║║▐█║║║║║║║║║║║
            ▐████████████████████████║▐█▀▀▀▀▀██▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║██║║║║║║║║║║██████████████║║║║║║║║║║║
            ║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║▀▀▀▀▀▀▀▀▀▀▀▀██║║║║║║║║║║║
            ║║║║▐█▌║║║║║║║║▄║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║║║║║
            ║║║║▐███████████║║║║║║║║║║║║║║║║║▀║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║
            ║║║║║▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║▄▄▄▄▄║║║║║█▌║║║║║║║║║║║║║║║▄▄▄▄▄▄▄▄║║║▐██║║║║║║║║║║║║║║║║║║║
            ║║║║║▐█████████║║║║║█▌║║║║║║║║║║║║║║▐████████▌║║║██║║║║║║║║║║║║║║║║║║║
            ║║║║║║███▀▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║██▌║▄▄██▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██║║║║║║║║║║║║███████▌║║║║║║║║║████████║▐████▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██▄███████║║║║██▀▀▀▀▀║║║║║║║║║║▀▀▀████║║║▀║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║▐████▀▀▀▀▀▀║║║║█▌║║║║║║║║║║║║║║║▄█████║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║▄║║║║║║█▌║║║║║║║║║║║║║║████▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║▀▀║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║▄▄▄▄▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║██████▄║║║║║║║║║║║║║║║║║║║▐████████████▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▄████║▀██████▄║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║█▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║▐███║║║║║║║▀████▌║║║║║║║║║║║║║║▐█║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▀║║║║║║║║║║║║▀▀║║║║║║║║║║║║║║║▐█▄█████████║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                손꾸락닷컴#3
            </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    
            ║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║
            ║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄▄▄║║║║║█▌║║║║║║║║║║
            ║║║║║║║║║║▄██▌║║║║║║║║║║║▄▄▄▄▄▄║║▄▄███▌║║║║║██████████║║║║█▌║║║║║║║║║║
            ║║║║║║║║▄████║║║║║║║║║║║▐██████▌▐███▀█▌║║║║║▀▀▀▀▀▀▀║██║║║║█▌║║║║║║║║║║
            ║║║║║▄████████▄║║║║║║║║║║║║║║║█▌║║║║▐█▌║║║║║║║║║║║║▄██║║║║██▄▄███║║║║║
            ║▄█████▀▀║║▀███████▄║║║║║║║║║██║║║║║██║║║║║║║█████████║║║▐█████▀▀║║║║║
            ║███▀▀║║║▄║║║║║▀▀███║║║║║║║║║██║║║║███║║║║║║▐██▀▀▀▀▀║║║║║║█▌║║║║║║║║║║
            ║║║║║║║║▐█║║║║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║▐██▄▄▄▄▄▄▄║║║▐█▌║║║║║║║║║║
            ║▄▄▄║║║║▐█║║║║║║║▄▄▄▄▄▄▄▄║▐█████████████║║║║║█████████║║║▐█║║║║║║║║║║║
            ▐████████████████████████║▐█▀▀▀▀▀██▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║██║║║║║║║║║║██████████████║║║║║║║║║║║
            ║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║▀▀▀▀▀▀▀▀▀▀▀▀██║║║║║║║║║║║
            ║║║║▐█▌║║║║║║║║▄║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║║██║║║║║║║║║║║
            ║║║║▐███████████║║║║║║║║║║║║║║║║║▀║║║║║║║║║║║║║║║║║║║║║║║█▌║║║║║║║║║║║
            ║║║║║▀▀▀▀▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║▄▄▄▄▄║║║║║█▌║║║║║║║║║║║║║║║▄▄▄▄▄▄▄▄║║║▐██║║║║║║║║║║║║║║║║║║║
            ║║║║║▐█████████║║║║║█▌║║║║║║║║║║║║║║▐████████▌║║║██║║║║║║║║║║║║║║║║║║║
            ║║║║║║███▀▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║██▌║▄▄██▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██║║║║║║║║║║║║███████▌║║║║║║║║║████████║▐████▌║║║║║║║║║║║║║║║║║║
            ║║║║║║██▄███████║║║║██▀▀▀▀▀║║║║║║║║║║▀▀▀████║║║▀║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║▐████▀▀▀▀▀▀║║║║█▌║║║║║║║║║║║║║║║▄█████║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║▄║║║║║║█▌║║║║║║║║║║║║║║████▀║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║║║║▀▀║║║║║║║║║║║║█▌║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║║║║║▄║║║║║║▄▄▄▄▄║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║██████▄║║║║║║║║║║║║║║║║║║║▐████████████▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▄████║▀██████▄║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║█▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║▐███║║║║║║║▀████▌║║║║║║║║║║║║║║▐█║║║║║║║║██▌║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║▀║║║║║║║║║║║║▀▀║║║║║║║║║║║║║║║▐█▄█████████║║║║║║║║║║║║║║║║║║║║
            ║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║██▀▀▀▀▀▀║║║║║║║║║║║║║║║║║║║║║║
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}